---
title: "CoolBeans"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CoolBeans}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# Load libraries:
library(CoolBeans)
library(tidyverse)
library(tidymodels)
library(missRanger)
library(missForest)
library(recipes)
library(glmnet)
library(rsample)
library(caret)
devtools::load_all()
# source(here::here("R/preprocessing.R"))
# source(here::here("R/split_data.R"))
# source(here::here("R/train_model.R"))
# source(here::here("R/test_model.R"))
```

Load data:

```{r load raw data}
#fpath <- system.file("data", "sim_data.rda", package = "CoolBeans")
#load(fpath) #since the data has been added to the loaded #not working path required
raw_data <- sim_data

# Data summary
summary(raw_data)

raw_data_boxplots <- raw_data %>%
  gather(key = "metabolite", value = "value", starts_with("metabolite"))
```

```{r plot raw data}
boxplot <- raw_data_boxplots %>%
  ggplot(aes(x = metabolite, y = value)) +
  geom_boxplot() +
  labs(x = "Metabolites", y = "Intensity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

boxplot
# ggsave(filename = "doc/images/raw_data_boxplots.png", plot = boxplot)
```

Data preprocessing:

```{r}
prep_data <- preprocessing(raw_data, "id", "exposure", start_metabolites = 5)

prep_data_boxplots <- prep_data %>%
  gather(key = "metabolite", value = "value", starts_with("metabolite"))

boxplot_prep <- prep_data_boxplots %>%
  ggplot(aes(x = metabolite, y = value)) +
  geom_boxplot() +
  labs(x = "Metabolites", y = "Intensity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

boxplot_prep
# ggsave(filename = "doc/images/prep_data_boxplots.png", plot = boxplot_prep)
```
Split data into training and testing datasets:

```{r}
data_split <- splitting(prep_data)
train_data <- data_split$train_data
test_data <- data_split$test_data
```

Feature selection.

Single metabolite models. Meti \~ β0P + β1C + ... + Ԑ

```{r}
sin_met <- sing_met_analysis(data=prep_data, train_data = train_data, exposure_feature = "target", start_metabolites = 4, covariates = "age", correction = "fdr")

sin_metabolites <- sin_met$results

met_pvalue <- sin_metabolites %>%
  ggplot2::ggplot(aes(x = yvar, y = p.value_corrected)) +
  geom_segment( aes(x=yvar, xend=yvar, y=0, yend=p.value_corrected), color="black") +
  geom_point( color="gray", size=2, alpha=0.6) +
  theme_light() +
  coord_flip() +
  labs(x = "Metabolites", y = "p-value") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  theme(axis.text.y = element_text(size = 5))

met_pvalue

sin_metabolites_filtered <- sin_metabolites[str_detect(sin_metabolites$term, "target"),] %>%
  filter(p.value_corrected < 0.01) %>%
  arrange(p.value_corrected)

selected_metabolites_id <- sin_metabolites_filtered$yvar

train_data <- train_data %>%
  select(c(id, target, selected_metabolites_id))

test_data <- test_data %>%
  select(c(id, target, selected_metabolites_id))
```

Trained model:

```{r}
trained_model <- training_lr(train_data)
trained_model
```

Testing model and results:

```{r}
results <- testing_lr(trained_model, test_data)
model_coeffs <- results$model_coefficients
model_coeffs

rmse_val <- results$rmse_val
rmse_val
# r_squared_val <- results$r_squared_val

coefficients <- model_coeffs$estimate
# feature_names <- names(coefficients)[-1] doesn't capture the name of the metabolites
feature_names <- model_coeffs$term[-1]

coefficients_df <- data.frame(feature = feature_names, coefficient = coefficients[-1])
coefficients_df
```
